<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="Expense_Calculator.aspx.cs" Inherits="a.Expense_Calculator" %>

<!DOCTYPE html>
<html lang="en">
<head runat="server">
    <title>Expense Management System</title>
    
    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons/font/bootstrap-icons.css" rel="stylesheet">

    <style>
        body {
/*            padding-top: 56px;*/
        }

        .expense-form {
            max-width: 450px;
            background: #ffffff;
            padding: 30px;
            border-radius: 10px;
            box-shadow: 0px 5px 15px rgba(0, 0, 0, 0.2);
            margin: 50px auto;
        }

        .gridview-container {
            margin-top: 30px;
            padding: 20px;
            background-color: white;
            border-radius: 8px;
            box-shadow: 0px 4px 8px rgba(0, 0, 0, 0.1);
        }

        .gridview-container table {
            width: 100%;
            border-collapse: collapse;
        }

        .gridview-container th {
            background-color: #001a66;
            color: white;
            padding: 12px;
            text-align: center;
            font-weight: bold;
        }

        .gridview-container td {
            padding: 10px;
            text-align: center;
            border-bottom: 1px solid #ddd;
        }

        .gridview-container tr:nth-child(even) {
            background-color: #f8f9fa;
        }

        .gridview-container tr:hover {
            background-color: #d6e9ff;
            transition: 0.3s;
        }

        .footer {
            background-color: #001a66;
            color: white;
            text-align: center;
            padding: 15px;
            margin-top: 30px;
        }

        .navbar-brand {
            font-weight: bold;
            font-size: 1.2rem;
        }

        .btn {
            transition: all 0.3s ease-in-out;
        }

        .btn:hover {
            opacity: 0.9;
        }
    </style>
</head>

<body class="bg-light">
    <form id="form1" runat="server">
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <div class="container">
                <a class="navbar-brand" href="User_dashboard.aspx">Expenses.web</a>
                <ul class="navbar-nav ms-auto">
                    <li class="nav-item"><a class="nav-link" href="ViewExpense.aspx"><i class="bi bi-list"></i> View Expenses</a></li>
                    <li class="nav-item"><a class="nav-link" href="Reports.aspx"><i class="bi bi-bar-chart"></i> Reports</a></li>
                </ul>
            </div>
        </nav>

        <div class="expense-form">
            <h2 class="text-center">Expense Tracker</h2>

            <div class="mb-3">
                <label class="form-label">Expense Name</label>
                <asp:TextBox ID="txtExpensName" runat="server" CssClass="form-control" placeholder="Enter expense name"></asp:TextBox>
            </div>

            <div class="mb-3">
                <label class="form-label">Price</label>
                <asp:TextBox ID="txtPrice" runat="server" CssClass="form-control" placeholder="Enter price"></asp:TextBox>
            </div>

            <div class="mb-3">
                <label class="form-label">Quantity</label>
                <asp:TextBox ID="txtQuantity" runat="server" CssClass="form-control" TextMode="Number" placeholder="Enter Quantity"></asp:TextBox>
            </div>

            <div class="mb-3">
                <label class="form-label">Date</label>
                <asp:TextBox ID="txtDate" runat="server" TextMode="Date" CssClass="form-control"></asp:TextBox>
            </div>

            <div class="mb-3">
                <label class="form-label">Payment Method</label>
                <asp:DropDownList ID="ddlPayMethod" runat="server" CssClass="form-control">
                    <asp:ListItem>Credit Card</asp:ListItem>
                    <asp:ListItem>Debit Card</asp:ListItem>
                    <asp:ListItem>Cash</asp:ListItem>
                    <asp:ListItem>UPI</asp:ListItem>
                </asp:DropDownList>
            </div>

            <asp:Button ID="btnAdd" runat="server" Text="Add Expense" CssClass="btn btn-primary w-100 mb-2" OnClick="btnAdd_Click"/>
            <asp:Button ID="btnUpdate" runat="server" Text="Update Expense" CssClass="btn btn-success w-100" OnClick="btnup_Click"/>
        </div>

        <div class="container">
            <div class="gridview-container">
                <asp:GridView ID="GVData" runat="server" AutoGenerateColumns="False" CssClass="table table-bordered table-hover"
                              AutoGenerateDeleteButton="True" AutoGenerateSelectButton="True"
                              OnSelectedIndexChanged="GVData_SelectedIndexChanged" DataKeyNames="Id" OnRowDeleting="GVData_RowDeleting">
                    <Columns>
                        <asp:BoundField DataField="Name" HeaderText="Expense Name" />
                        <asp:BoundField DataField="Price" HeaderText="Price" />
                        <asp:BoundField DataField="Quantity" HeaderText="Quantity" />
                        <asp:BoundField DataField="TotalAmount" HeaderText="Total Amount" />
                        <asp:BoundField DataField="Exp_Created" HeaderText="Date" />
                        <asp:BoundField DataField="Payment_Method" HeaderText="Payment Method" />
                    </Columns>
                </asp:GridView>
            </div>
        </div>

        <footer class="footer">
            <p>&copy; 2025 Expenses.web. All rights reserved.</p>
        </footer>
    </form>
</body>
</html>
