<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="Reports.aspx.cs" Inherits="a.Reports" %>

<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title>View Expenses - Retro Paper Style</title>

    <!-- ✅ Bootstrap & Icons -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"/>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons/font/bootstrap-icons.css" rel="stylesheet"/>

    <!-- ✅ Google Font (Pixelated) -->
    <link href="https://fonts.googleapis.com/css2?family=Press+Start+2P&display=swap" rel="stylesheet"/>

    <style>
        * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
            scroll-behavior: smooth;
        }

        body {
            font-family: 'Press Start 2P', cursive;
            background: url('background.jpg') no-repeat center center fixed;
            background-size: cover;
            text-align: center;
            color: black; /* Better contrast for paper theme */
        }

        h1{
            color: #001a66;
        }

        /* ✅ Navigation Bar */
        .navbar {
            background: #001a66;
            padding: 15px;
            text-align: left;
        }

        .navbar a {
            color: white;
            text-decoration: none;
            font-size: 14px;
            padding: 10px 20px;
            display: inline-block;
            border: 3px solid white;
            box-shadow: 3px 3px 0px black;
        }

        .navbar a:hover {
            background: white;
            color: black;
        }

        /* ✅ Paper-Like Container */
        .gridview-container {
            width: 95%;
            max-width: 1200px;
            margin: 50px auto;
            padding: 20px;
            background: #f9f5ec; /* Light beige paper color */
            border: 6px dotted #bfbfbf; /* Dotted border like a notebook */
            box-shadow: 6px 6px 0px rgba(0, 0, 0, 0.2); /* Subtle shadow */
            border-radius: 12px;
            overflow: hidden;
        }

        /* ✅ Table Styling */
        .gridview-container table {
            width: 100%;
            border-collapse: collapse;
            background: #fdfdfd; /* White background for table */
            text-align: center;
        }

        .gridview-container th, .gridview-container td {
            padding: 12px;
            text-align: center;
            border-bottom: 2px solid #bfbfbf;
            color: black;
        }

        .gridview-container th {
            background: #f1e7d0; /* Light cream color for header */
            color: black;
            text-transform: uppercase;
            font-size: 14px;
            border-bottom: 3px solid #bfbfbf;
        }

        /* ✅ Alternate Row Colors */
        .gridview-container tr:nth-child(even) {
            background: #fcf8f3; /* Light paper shade */
        }

        .gridview-container tr:nth-child(odd) {
            background: #fff; /* White */
        }

        /* ✅ Button Styling */
        .gridview-container a {
            background: #f1e7d0;
            color: black;
            text-decoration: none;
            font-size: 14px;
            padding: 5px 10px;
            display: inline-block;
            border: 2px solid #bfbfbf;
            box-shadow: 3px 3px 0px #bfbfbf;
        }

        .gridview-container a:hover {
            background: #e6dac9;
            color: black;
        }

    </style>
</head>
<body>

    <!-- ✅ Navigation Bar -->
    <div class="navbar">
        <a href="Expense_Calculator.aspx">🔙 Go Back to Expense Calculator</a>
    </div>

    <div>
        <br>
        <h1>MANAGE YOUR EXPENSES HERE.</h1>
    </div>

    <form id="form1" runat="server">

        <div class="container gridview-container">
            <h2>Expense Analysis</h2>
            <canvas id="expenseChart"></canvas>
        </div>

        <!-- ✅ GridView in Retro Paper Container -->
        <div class="container gridview-container">
            <h2>View Expenses</h2>
           <asp:GridView ID="GVData" runat="server" 
                AutoGenerateColumns="False" 
                DataKeyNames="Id"
                CssClass="table table-bordered"
                AutoGenerateDeleteButton="True"
                AutoGenerateSelectButton="True"
                OnSelectedIndexChanged="GVData_SelectedIndexChanged"
                OnRowDeleting="GVData_RowDeleting">


                <Columns>
                    <asp:BoundField DataField="Id" HeaderText="ID" ItemStyle-Width="10%" />
                    <asp:BoundField DataField="Name" HeaderText="Expense Name" ItemStyle-Width="20%" />
                    <asp:BoundField DataField="price" HeaderText="Price" ItemStyle-Width="15%" />
                    <asp:BoundField DataField="quantity" HeaderText="Quantity" ItemStyle-Width="10%" />
                    <asp:BoundField DataField="TotalAmount" HeaderText="Amount" ItemStyle-Width="10%" />
                    <asp:BoundField DataField="Exp_Created" HeaderText="Date" DataFormatString="{0:yyyy-MM-dd}" ItemStyle-Width="10%" />
                    <asp:BoundField DataField="Payment_Method" HeaderText="Payment Method" ItemStyle-Width="15%" />
                    <asp:BoundField DataField="description" HeaderText="Description" ItemStyle-Width="10%" />
                </Columns>

            </asp:GridView>

            <asp:Button ID="btnExportCSV" runat="server" Text="📥 Export to CSV" CssClass="btn btn-primary" />

        </div>

    </form>
</body>
</html>

<script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
<script type="text/javascript">
    function loadChart(labels, data) {
        var ctx = document.getElementById('expenseChart').getContext('2d');
        new Chart(ctx, {
            type: 'line',
            data: {
                labels: labels,
                datasets: [{
                    label: 'Total Amount (₹)',
                    data: data,
                    borderColor: '#007bff',
                    backgroundColor: 'rgba(0, 123, 255, 0.2)',
                    borderWidth: 2
                }]
            }
        });
    }
</script>
